package com.ads.model;

import java.io.Serializable;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class Oper implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper.id
     * 
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper.user_name
     * 
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper.password
     * 
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper.email
     * 
     */
    private String email;

    /**
     * oper表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 oper.id的get方法 
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 数据字段 oper.id的set方法
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 数据字段 oper.user_name的get方法 
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 数据字段 oper.user_name的set方法
     * 
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 数据字段 oper.password的get方法 
     * 
     */
    public String getPassword() {
        return password;
    }

    /**
     * 数据字段 oper.password的set方法
     * 
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * 数据字段 oper.email的get方法 
     * 
     */
    public String getEmail() {
        return email;
    }

    /**
     * 数据字段 oper.email的set方法
     * 
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}