package com.ads.qry;

import lombok.Data;

import java.math.BigDecimal;

/**
 * @author zhuxd@wjs.com
 * @date 2017/8/12 3:52
 */

@Data
public class AdsEditQry{
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.id
	 *
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.ads_name
	 *
	 */
	private String adsName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.ads_type
	 *
	 */
	private String adsType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.announce_no
	 *
	 */
	private Integer announceNo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.click_no
	 *
	 */
	private Integer clickNo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.position
	 *
	 */
	private String position;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.show_rate
	 *
	 */
	private BigDecimal showRate;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.validate_time
	 *
	 */
	private Long validateTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.statuse
	 *
	 */
	private String statuse;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.needs_origin
	 *
	 */
	private String needsOrigin;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.feedback_score
	 *
	 */
	private Integer feedbackScore;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column ads.note
	 *
	 */
	private String note;
}
